///bill
export const FETCH_BILL_ACTION = 'FETCH_BILL_ACTION';
export const FETCH_BILL_ACTION_SUCCESS = 'FETCH_BILL_ACTION_SUCCESS';
export const FETCH_BILL_ACTION_FAIL = 'FETCH_BILL_ACTION_FAIL';
export const UPDATE_BILL_STATUS_ORDER_ACTION = 'UPDATE_BILL_STATUS_ORDER_ACTION';
export const UPDATE_BILL_STATUS_ORDER_ACTION_SUCCESS = 'UPDATE_BILL_STATUS_ORDER_ACTION_SUCCESS';
export const UPDATE_BILL_STATUS_ORDER_ACTION_FAIL = 'UPDATE_BILL_STATUS_ORDER_ACTION_FAIL';
export const UPDATE_BILL_STATUS_PAY_ACTION = 'UPDATE_BILL_STATUS_PAY_ACTION';
export const UPDATE_BILL_STATUS_PAY_ACTION_SUCCESS = 'UPDATE_BILL_STATUS_PAY_ACTION_SUCCESS';
export const UPDATE_BILL_STATUS_PAY_ACTION_FAIL = 'UPDATE_BILL_STATUS_PAY_ACTION_FAIL';
export const RETURN_BILL_ACTION = 'RETURN_BILL_ACTION';
export const RETURN_BILL_ACTION_SUCCESS = 'RETURN_BILL_ACTION_SUCCESS';
export const RETURN_BILL_ACTION_FAIL = 'RETURN_BILL_ACTION_FAIL';
//bill detail
export const FETCH_BILL_DETAIL_ACTION = 'FETCH_BILL_DETAIL_ACTION';
export const FETCH_BILL_DETAIL_ACTION_SUCCESS = 'FETCH_BILL_DETAIL_ACTION_SUCCESS';
export const FETCH_BILL_DETAIL_ACTION_FAIL = 'FETCH_BILL_DETAIL_ACTION_FAIL';
export const UPDATE_BILL_DETAIL_ACTION = 'UPDATE_BILL_DETAIL_ACTION';
export const UPDATE_BILL_DETAIL_ACTION_SUCCESS = 'UPDATE_BILL_DETAIL_ACTION_SUCCESS';
export const UPDATE_BILL_DETAIL_ACTION_FAIL = 'FETCH_BILL_DETAIL_ACTION_FAIL';
// bill return
export const FETCH_BILL_RETURN_ACTION = 'FETCH_BILL_RETURN_ACTION';
export const FETCH_BILL_RETURN_ACTION_SUCCESS = 'FETCH_BILL_RETURN_ACTION_SUCCESS';
export const FETCH_BILL_RETURN_ACTION_FAIL = 'FETCH_BILL_RETURN_ACTION_FAIL';
export const CREATE_BILL_RETURN_ACTION = 'CREATE_BILL_RETURN_ACTION';
export const CREATE_BILL_RETURN_ACTION_SUCCESS = 'CREATE_BILL_RETURN_ACTION_SUCCESS';
export const CREATE_BILL_RETURN_ACTION_FAIL = 'CREATE_BILL_RETURN_ACTION_FAIL';
export const UPDATE_BILL_RETURN_ACTION = 'UPDATE_BILL_RETURN_ACTION';
export const UPDATE_BILL_RETURN_ACTION_SUCCESS = 'UPDATE_BILL_RETURN_ACTION_SUCCESS';
export const UPDATE_BILL_RETURN_ACTION_FAIL = 'FETCH_BILL_RETURN_ACTION_FAIL';
// bill return detail
export const FETCH_BILL_RETURN_DETAIL_ACTION = 'FETCH_BILL_RETURN_DETAIL_ACTION';
export const FETCH_BILL_RETURN_DETAIL_ACTION_SUCCESS = 'FETCH_BILL_RETURN_DETAIL_ACTION_SUCCESS';
export const FETCH_BILL_RETURN_DETAIL_ACTION_FAIL = 'FETCH_BILL_RETURN_DETAIL_ACTION_FAIL';
export const CREATE_BILL_RETURN_DETAIL_ACTION = 'CREATE_BILL_RETURN_DETAIL_ACTION';
export const CREATE_BILL_RETURN_DETAIL_ACTION_SUCCESS = 'CREATE_BILL_RETURN_DETAIL_ACTION_SUCCESS';
export const CREATE_BILL_RETURN_DETAIL_ACTION_FAIL = 'CREATE_BILL_RETURN_DETAIL_ACTION_FAIL';
export const UPDATE_BILL_RETURN_DETAIL_ACTION = 'UPDATE_BILL_RETURN_DETAIL_ACTION';
export const UPDATE_BILL_RETURN_DETAIL_ACTION_SUCCESS = 'UPDATE_BILL_RETURN_DETAIL_ACTION_SUCCESS';
export const UPDATE_BILL_RETURN_DETAIL_ACTION_FAIL = 'FETCH_BILL_RETURN_DETAIL_ACTION_FAIL';
export const ADD_ITEM_ACTION = 'ADD_ITEM_ACTION';
export const ADD_ITEM_ACTION_SUCCESS = 'ADD_ITEM_ACTION_SUCCESS';
export const ADD_ITEM_ACTION_FAIL = 'ADD_ITEM_ACTION_FAIL';
export const REMOTE_ITEM_ACTION = 'REMOTE_ITEM_ACTION';
export const REMOTE_ITEM_ACTION_SUCCESS = 'REMOTE_ITEM_ACTION_SUCCESS';
export const REMOTE_ITEM_ACTION_FAIL = 'REMOTE_ITEM_ACTION_FAIL';
export const UPDATE_ITEM_ACTION = 'UPDATE_ITEM_ACTION';
export const UPDATE_ITEM_ACTION_SUCCESS = 'UPDATE_ITEM_ACTION_SUCCESS';
export const UPDATE_ITEM_ACTION_FAIL = 'UPDATE_ITEM_ACTION_FAIL';

//staff
export const FETCH_STAFF_ACTION = 'FETCH_STAFF_ACTION';
export const FETCH_STAFF_ACTION_SUCCESS = 'FETCH_STAFF_ACTION_SUCCESS';
export const FETCH_STAFF_ACTION_FAIL = 'FETCH_STAFF_ACTION_FAIL';
export const CREATE_STAFF_ACTION = 'CREATE_STAFF_ACTION';
export const CREATE_STAFF_ACTION_SUCCESS = 'CREATE_STAFF_ACTION_SUCCESS';
export const CREATE_STAFF_ACTION_FAIL = 'CREATE_STAFF_ACTION_FAIL';
export const UPDATE_STAFF_ACTION = 'UPDATE_STAFF_ACTION';
export const UPDATE_STAFF_ACTION_SUCCESS = 'UPDATE_STAFF_ACTION_SUCCESS';
export const UPDATE_STAFF_ACTION_FAIL = 'UPDATE_STAFF_ACTION_FAIL';
export const REPASSWORD_STAFF_ACTION = 'REPASSWORD_STAFF_ACTION';
export const REPASSWORD_STAFF_ACTION_SUCCESS = 'REPASSWORD_STAFF_ACTION_SUCCESS';
export const REPASSWORD_STAFF_ACTION_FAIL = 'REPASSWORD_STAFF_ACTION_FAIL';