///bill
export const FETCH_BILL_ACTION = 'FETCH_BILL_ACTION';
export const FETCH_BILL_ACTION_SUCCESS = 'FETCH_BILL_ACTION_SUCCESS';
export const FETCH_BILL_ACTION_FAIL = 'FETCH_BILL_ACTION_FAIL';
export const FETCH_FORM_BILL_ACTION = 'FETCH_FORM_BILL_ACTION';
export const FETCH_FORM_BILL_ACTION_SUCCESS = 'FETCH_FORM_BILL_ACTION_SUCCESS';
export const FETCH_FORM_BILL_ACTION_FAIL = 'FETCH_FORM_BILL_ACTION_FAIL';
export const UPDATE_BILL_STATUS_ORDER_ACTION = 'UPDATE_BILL_STATUS_ORDER_ACTION';
export const UPDATE_BILL_STATUS_ORDER_ACTION_SUCCESS = 'UPDATE_BILL_STATUS_ORDER_ACTION_SUCCESS';
export const UPDATE_BILL_STATUS_ORDER_ACTION_FAIL = 'UPDATE_BILL_STATUS_ORDER_ACTION_FAIL';
export const UPDATE_BILL_STATUS_PAY_ACTION = 'UPDATE_BILL_STATUS_PAY_ACTION';
export const UPDATE_BILL_STATUS_PAY_ACTION_SUCCESS = 'UPDATE_BILL_STATUS_PAY_ACTION_SUCCESS';
export const UPDATE_BILL_STATUS_PAY_ACTION_FAIL = 'UPDATE_BILL_STATUS_PAY_ACTION_FAIL';
export const RETURN_BILL_ACTION = 'RETURN_BILL_ACTION';
export const RETURN_BILL_ACTION_SUCCESS = 'RETURN_BILL_ACTION_SUCCESS';
export const RETURN_BILL_ACTION_FAIL = 'RETURN_BILL_ACTION_FAIL';
//bill detail
export const FETCH_BILL_DETAIL_ACTION = 'FETCH_BILL_DETAIL_ACTION';
export const FETCH_BILL_DETAIL_ACTION_SUCCESS = 'FETCH_BILL_DETAIL_ACTION_SUCCESS';
export const FETCH_BILL_DETAIL_ACTION_FAIL = 'FETCH_BILL_DETAIL_ACTION_FAIL';
export const UPDATE_BILL_DETAIL_ACTION = 'UPDATE_BILL_DETAIL_ACTION';
export const UPDATE_BILL_DETAIL_ACTION_SUCCESS = 'UPDATE_BILL_DETAIL_ACTION_SUCCESS';
export const UPDATE_BILL_DETAIL_ACTION_FAIL = 'FETCH_BILL_DETAIL_ACTION_FAIL';

//staff
export const FETCH_STAFF_ACTION = 'FETCH_STAFF_ACTION';
export const FETCH_STAFF_ACTION_SUCCESS = 'FETCH_STAFF_ACTION_SUCCESS';
export const FETCH_STAFF_ACTION_FAIL = 'FETCH_STAFF_ACTION_FAIL';
export const CREATE_STAFF_ACTION = 'CREATE_STAFF_ACTION';
export const CREATE_STAFF_ACTION_SUCCESS = 'CREATE_STAFF_ACTION_SUCCESS';
export const CREATE_STAFF_ACTION_FAIL = 'CREATE_STAFF_ACTION_FAIL';
export const UPDATE_STAFF_ACTION = 'UPDATE_STAFF_ACTION';
export const UPDATE_STAFF_ACTION_SUCCESS = 'UPDATE_STAFF_ACTION_SUCCESS';
export const UPDATE_STAFF_ACTION_FAIL = 'UPDATE_STAFF_ACTION_FAIL';
export const REPASSWORD_STAFF_ACTION = 'REPASSWORD_STAFF_ACTION';
export const REPASSWORD_STAFF_ACTION_SUCCESS = 'REPASSWORD_STAFF_ACTION_SUCCESS';
export const REPASSWORD_STAFF_ACTION_FAIL = 'REPASSWORD_STAFF_ACTION_FAIL';